### ISSUE TITLE
Fix Main Site Logo

### ISSUE THREAD

**Issue by andrewferguson** [louis-threedots/website#2]
As per discussions on Slack, the logo on the site should be changed to one that both reflects the braille, but also that won't confuse new visitors to the site. To this end I have made an SVG logo (very basic, literally just a copy-paste of the text from the website). Attached are two versions, the raw SVG for the site, and the Inkscape SVG if any edits need to be made later (as this version supports easier editing). They're attached in a single ZIP: [website_logos.zip](https://github.com/louis-threedots/website/files/4432590/website_logos.zip), because GitHub doesn't allow SVGs.... just great.

The required font, Comfortaa Bold, is not embedded in the SVG and will need to be included. I don't know if React / Gatsby supports a better way of managing fonts, but one easy way of getting the font is through Google Fonts:
`<link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet'>`

I made this an issue rather than a PR because I looked at the [logo page](https://github.com/louis-threedots/website/blob/master/src/components/logo.js) and thought ...... nope! (I know a bit of React but GraphQL is knew to me). I think I'd be better leaving it to someone who actually knows what they're doing, rather than trying to bodge it myself!

**Comment by GregBrimble** [comment]
Added! https://github.com/louis-threedots/website/blob/master/src/images/logo.svg

And deployed! https://louis-threedots.github.io/website/

**Comment by GregBrimble** [comment]
Thanks for making the image @andrewferguson :)
