### ISSUE TITLE
Link to the official comments page

### ISSUE THREAD

**Issue by GregBrimble** [louis-threedots/website#9]
Maybe? Or use or own? Didn't quite understand the email.

> The link to your public comments should be clearly present in your website:
> 
> - If you have already included a comment system on your website feel free to use it.
> 
> - If you don't, from your website link to the comment page created for your group:
> 
> https://sdp2020.gitlab.io/posts/group10/

**Comment by Canbenix** [comment]
For our comment system you are required to log in to GitHub which is a downside.

**Comment by GregBrimble** [comment]
Ah, yes. Didn't notice. We could use Disqus or something instead, but at
that point, I guess we might as well just use theirs (no matter how ugly it
is).

**Comment by GregBrimble** [comment]
LINK TO THEIRS
